### ISSUE TITLE
maven plugin

### ISSUE THREAD

**Issue by alanngai** [lightbend/reactive-app-maven-plugin#14]
parent of lightbend/reactive-app-maven-plugin#19
parent of lightbend/reactive-app-maven-plugin#17
parent of lightbend/reactive-app-maven-plugin#10
parent of lightbend/reactive-app-maven-plugin#9
parent of lightbend/reactive-app-maven-plugin#8
parent of lightbend/reactive-app-maven-plugin#4
parent of lightbend/reactive-app-maven-plugin#20
parent of lightbend/reactive-app-maven-plugin#41
parent of lightbend/reactive-app-maven-plugin#43
parent of lightbend/reactive-app-maven-plugin#44

**Comment by alanngai** [comment]
added ticket lightbend/reactive-app-maven-plugin#20 to track java-maven-chirper example

**Comment by dwijnand** [comment]
All done

**Comment by dwijnand** [comment]
Let's not keep using this phantom ticket.

All issues in this repo are about the maven plugin. We don't need a label and a parent issue for every issue.

**Comment by eed3si9n** [comment]
Maybe we can rename this issue to "can we ship it?" to clarify the purpose.

**Comment by dwijnand** [comment]
I think that's best discussed as a team, than with issue mechanics.
