### ISSUE TITLE
Document Cinnamon integration

### ISSUE THREAD

**Issue by TimMoore** [lightbend/reactive-app-maven-plugin#16]
Looking at [the documentation for Cinnamon integration in Maven](https://developer.lightbend.com/docs/cinnamon/current/setup/cinnamon-agent-maven.html) and this plugin, it isn't clear to me whether or not they will work together. Specifically, whether the instructions for automating download of `cinnamon-agent.jar` and adding it to the Java command line will be used with the Docker image generation.

A customer also posted to the Discourse forum trying to get this to work: https://discuss.lightbend.com/t/cinnamon-agent-jar-not-included-in-docker-image/1004

Eventually this was raised in support: https://support.lightbend.com/agent/case/10864

@mitkus provided a solution for the docker-maven-plugin, which might also apply here:

> We can define inline assembly rule for docker-maven-plugin to put cinnamon-agent inside our docker image like this:
>
> ```xml
> <images>
>   <image>
>     ...
>     <build>
>       <assembly>
>          <descriptorRef>artifact-with-dependencies</descriptorRef>
>          <inline>
>            <dependencySets>
>              <dependencySet>
>               <includes>
>                 <include>com.lightbend.cinnamon:cinnamon-agent</include>
>               </includes>
>               <outputDirectory>./jars</outputDirectory>
>             </dependencySet>
>           </dependencySets>
>         </inline>
>       </assembly>
>     </build>
>   </image>
> </images>
> ```
> 
> And then add appropriate flags to use the agent:
> 
> ```xml
> <images>
>   <image>
>     ...
>     <entryPoint>
>       <exec>
>         <arg>java</arg>
>         <arg>-javaagent:./jars/cinnamon-agent.jar</arg>
>         <arg>/opt/demo/server.jar</arg>
>         ...
>       </exec>
>     </entryPoint>
>   </image>
> </images>
> ```

**Comment by TimMoore** [comment]
Related: https://github.com/lagom/lagom-recipes/pull/31

It's an example of using a Lagom service with Cinnamon via the `exec-maven-plugin` (similar to https://developer.lightbend.com/docs/cinnamon/current/setup/cinnamon-agent-maven.html)

**Comment by alanngai** [comment]
@jsravn do we have a ticket for the change necessary to generate a container image with cinnamon enabled?  I thought I saw it at one point, but I can't seem to find it now.  If you have it, can you reference it in this ticket?

**Comment by alanngai** [comment]
there is work in progress for es documentation that should cover this (es-backend/issues/174).  We can leave this ticket as is to pull out the part of that documentation into a more general LBO cinnamon documentation section

**Comment by dwijnand** [comment]
I'll try working on this.

**Comment by jsravn** [comment]
FYI sbt-reactive-app + cinnamon plugin works - it enables the cinnamon agent in the docker image.

**Comment by alanngai** [comment]
@dwijnand any updates (for the standup) regarding this?
