### ISSUE TITLE
update lagom-java-maven-chirper-example to use the plugin

### ISSUE THREAD

**Issue by alanngai** [lightbend/reactive-app-maven-plugin#20]
update of https://github.com/lagom/lagom-java-maven-chirper-example to plugin

Right now, it contains K8s & DC/OS deployment files using an outdated approach. The Kubernetes instructions point to the old, StatefulSet-based approach, and the DC/OS instructions point to https://developer.lightbend.com/guides/lagom-dcos-marathon-deploy-microservices/, which now returns a 404 error.

In the past, the ConductR/ES platform team has used the Chirper project as a test bed, so this might happen as a natural consequence of finishing the Maven plugin (particularly #10), but I wanted to double-check. If you're not planning to do this, let me know and I can add it to our own backlog once the documentation for this is available. In the meantime, we might remove the existing (outdated) deployment information.

**Comment by dwijnand** [comment]
> and the DC/OS instructions point to https://developer.lightbend.com/guides/lagom-dcos-marathon-deploy-microservices/, which now returns a 404 error

@TimMoore lol turns out that's because it needs to still be reviewed and merged 😀

https://github.com/typesafehub/prod-suite-management-doc/pull/25
