### ISSUE TITLE
Clean up integration tests

### ISSUE THREAD

**Issue by mitkus** [lightbend/reactive-app-maven-plugin#8]
- Not depend on hardcoded plugin version anymore
- If possible, avoid installing snapshot build of plugin locally every time before running tests

**Comment by dwijnand** [comment]
@mitkus @alanngai apologies: I auto-closed this via merging https://github.com/lightbend/reactive-app-maven-plugin/pull/18. See https://github.com/lightbend/reactive-app-maven-plugin/pull/18#issuecomment-402800487 for my reasoning. In future I'll use the "Review" column instead.
