### ISSUE TITLE
Fix multi-project builds

### ISSUE THREAD

**Issue by mitkus** [lightbend/reactive-app-maven-plugin#9]
This happens in some multi-project builds:

```
Failed to execute goal com.lightbend.rp:reactive-app-maven-plugin:0.3.0:build (build-docker) on project hello-impl: Execution build-docker of goal com.lightbend.rp:reactive-app-maven-plugin:0.3.0:build failed: java.lang.ClassNotFoundException: com.lightbend.lagom.internal.api.tools.ServiceDetector$
```

Seems to be related to lagom endpoint discovery magic.  

This error should be occuring on the [maven chirper](https://github.com/lagom/lagom-java-maven-chirper-example/) project

**Comment by cunei** [comment]
It seems some needed libraries are not included. This diff makes install for all projects succeed, except for front-end: https://github.com/cunei/lagom-java-maven-chirper-example/commit/d9c20108cb5aab5f4320aa0a7cbfdd15c8e1c617

**Comment by alanngai** [comment]
@mitkus can you provide some insight?

**Comment by dwijnand** [comment]
I was able to take it a little step further and get front-end to pass too:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] lagom-java-chirper 1.0.0-SNAPSHOT .................. SUCCESS [  0.834 s]
[INFO] friend-api ......................................... SUCCESS [  0.998 s]
[INFO] friend-impl ........................................ SUCCESS [ 27.116 s]
[INFO] chirp-api .......................................... SUCCESS [  0.165 s]
[INFO] chirp-impl ......................................... SUCCESS [ 29.778 s]
[INFO] activity-stream-api ................................ SUCCESS [  0.081 s]
[INFO] activity-stream-impl ............................... SUCCESS [  7.881 s]
[INFO] load-test-api ...................................... SUCCESS [  0.074 s]
[INFO] load-test-impl ..................................... SUCCESS [  2.807 s]
[INFO] front-end 1.0.0-SNAPSHOT ........................... SUCCESS [ 11.391 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2018-07-17T17:57:17+01:00
[INFO] ------------------------------------------------------------------------
```

https://github.com/dwijnand/lagom-java-maven-chirper-example/tree/add-reactive-app-maven-plugin

But what is expected and what's not expected of a consumer of either sbt or maven plugin? 🤔

**Comment by mitkus** [comment]
Ok, I think some historical context might be useful here to better understand why some choices were made.

sbt plugin was built in a mindset that it should do as much as possible automatically. In an ideal case, you just do `addSbtPlugin(...)` and that makes your project run in k8s / dcos. However, we found that this approach has its own problems - it hides the details of what's going on from the user and makes it hard to understand/debug any issues that arise. Especially with our limited support bandwidth, it seemed not be a viable approach.

So we were discussing with @dbrinegar for some time that it would be good to move Lightbend Orchestration in a direction of "less magic". That is, make everything more transparent, do less automation and more documentation. Silent automatic features could be turned into lint-style checks, so that user would have a better understanding of what's going on. For example, maven build plugin asks you to manually add the right dependencies and checks for them at build time.

This file has the logic for dependency checking that we do now: https://github.com/lightbend/reactive-app-maven-plugin/blob/master/src/main/java/com/lightbend/rp/ReactiveLibChecker.java. To me it sounds like this ticket is mostly about improving this checking.

Of course, it's hard to say where is the line to draw with this manual approach. At an extreme end, we might not need Lightbend Orchestration at all since everything can be accomplished with `akka-management` and good documentation. That's a question for further discussion, I guess.

**Comment by dwijnand** [comment]
Thanks @mitkus for the comment and running me through this on Hangout.

Here are the action items to complete this:

- [ ] Add api-tools dependency checking logic, don't throw `java.lang.ClassNotFoundException: com.lightbend.lagom.internal.api.tools.ServiceDetector$`
- [ ] Mention the api-tools dependency in the README, where the other dependencies are mentioned
- [ ] Exclude `lagom-javadsl-client` in https://github.com/lightbend/reactive-app-maven-plugin/blob/d6ce0f3969632019dcda9321fab75d19d4e32aa8/src/main/java/com/lightbend/rp/AppTypeDetector.java#L18 to avoid:

```
    Caused by: java.lang.ClassCastException: class play.api.inject.guice.GuiceApplicationLoader
        at java.lang.Class.asSubclass (Class.java:3404)
        at com.lightbend.lagom.internal.api.tools.ServiceDetector$.services (ServiceDetector.scala:58)
        at com.lightbend.lagom.internal.api.tools.ServiceDetector$.services (ServiceDetector.scala:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:498)
        at com.lightbend.rp.LagomApp.apply (LagomApp.java:89)
```
